export const introText = {
  title: "#1 HIRING ",
  titleGreen: "PLATFORM",
  subTitle: "Das perfekte Match für Unternehmen und Arbeitnehmer aus ",
  subTitleGreen: "TECH",
  findButton: "Kandidaten finden",
  listButtons: [
    "Java",
    "JavaScript",
    "Spring",
    "Angular",
    "Python",
    ".NET",
    "C#",
    "Microsoft Azure",
    "SQL",
    "Spring Boot",
    "Cloud Computing",
    "Cloud Infrastructure",
    "TypeScript",
    "Amazon Web Services (AWS)",
    "SAP ABAP",
  ],
  searchText: "Beliebte Schwerpunkte unserer Kandidaten",
};
